name: Linter

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    lint:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            
            - name: Install dependencies
              run: pnpm install

            - name: Run linters
              run: pnpm run lint